# Generated by Django 4.2.16 on 2024-11-24 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=6)),
                ('fin_co_no', models.CharField(max_length=10)),
                ('fin_prdt_cd', models.CharField(max_length=10)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('join_way', models.TextField()),
                ('loan_inci_expn', models.TextField()),
                ('erly_rpay_fee', models.TextField()),
                ('dly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_lmt', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dcls_strt_day', models.DateField(blank=True, null=True)),
                ('dcls_end_day', models.DateField(blank=True, null=True)),
                ('fin_co_subm_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpay_typ', models.CharField(max_length=50)),
                ('rpay_type_nm', models.CharField(max_length=100)),
                ('lend_rate_type', models.CharField(max_length=50)),
                ('lend_rate_type_nm', models.CharField(max_length=100)),
                ('lend_rate_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lend_rate_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lend_rate_avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='loan.loanproducts')),
            ],
        ),
    ]
