# Generated by Django 4.2.16 on 2024-11-23 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, error_messages={'unique': '닉네임이 중복되었습니다.'}, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^010-\\d{4}-\\d{4}$')]),
        ),
    ]
